# Generated by Django 5.2.1 on 2025-05-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textresources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textresource',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='uploaded_texts/'),
        ),
        migrations.AlterField(
            model_name='textresource',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
